# Generated by Django 5.0.4 on 2024-04-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='Default description', max_length=255),
            preserve_default=False,
        ),
    ]
